const products = [
  {
    id: 0,
    name: "Czarny skórzany portfel",
    description: `Portfel wykonany z wysokiej jakości skóry naturalnej. Zamykany na suwak. Wewnątrz kieszeń na banknoty,
     miejsce na karty lub dokumenty.`,
    category: "Portfele",
    price: 319.99,
    image: "./ikony/1_portfel.jpg",
    sale: true,
    saleAmount: 20,
  },
  {
    id: 1,
    name: "Portfel męski",
    description: `Elegancki portfel męski wykonany ze skóry naturalnej w koniakowym kolorze.`,
    category: "Portfele",
    price: 219.99,
    image: "./ikony/2_portfel.jpg",
  },
  {
    id: 2,
    name: "Pasek męski",
    description: `Elegancki pasek męski wykonany w formie plecionki.`,
    category: "Paski",
    price: 69.99,
    image: "./ikony/3_pasek.jpg",
  },
  {
    id: 3,
    name: "Brązowy skórzany pasek męski",
    description: `Pasek męski wykonany z wysokogatunkowej skóry naturalnej w brązowym kolorze.`,
    category: "Paski",
    price: 99.99,
    image: "./ikony/4_pasek.jpg",
  },
  {
    id: 4,
    name: "Skórzana torebka damska w kolorze czarnym",
    description: `Torebka damska o trapezowym kształcie wykonana ze skóry naturalnej. Zamykana na suwak,
     jednokomorowa z logowaną podszewką. Wewnątrz jedna kieszeń na suwak i jedna otwarta kieszonka.`,
    category: "Torebki damskie",
    price: 519.99,
    image: "./ikony/5_torebka.jpg",
  },
  {
    id: 5,
    name: "Torebka damska",
    description: `Torebka damska o formie niewielkiej kopertówki. Wykonana ze skóry naturalnej w kolorze khaki. `,
    category: "Torebki damskie",
    price: 299.99,
    image: "./ikony/6_torebka.jpg",
    sale: true,
    saleAmount: 99.99,
  },
  {
    id: 6,
    name: "Duża torebka skórzana damska",
    description: `Duża torebka damska typu shopper wykonana ze skóry naturalnej. Zamykana suwakiem. 
    Jednokomorowa, nieusztywniana z logowaną podszewką. `,
    category: "Torebki damskie",
    price: 399.99,
    image: "./ikony/7_torebka.jpg",
  },
  {
    id: 7,
    name: "Skórzane czarne etui na klucze damskie",
    description: `Etui na klucze wykonane ze skóry naturalnej.`,
    category: "Etui na klucze",
    price: 179.99,
    image: "./ikony/8_etui.jpg",
  },
  {
    id: 8,
    name: "Damskie etui",
    description: `Etui wykonane z naturalnej skóry. `,
    category: "Etui na klucze",
    price: 299.99,
    image: "./ikony/9_etui.jpg",
    sale: true,
    saleAmount: 9.99,
  },
];
